# -------------------------------
# MapProxy NA 4326 configuration.
# -------------------------------

services:
  #sets up how to make the source data available
  demo:
  tms:
  wms:
    #srs sets the coordinate reference systems as which you want to make your data available. MapProxy reprojects the source data very well to these projections.
    srs: ['EPSG:4326']
    image_formats: ['image/jpeg', 'image/png']
    md:
      # metadata used in capabilities documents
      title: MapProxy WMS Proxy
      abstract: A MapProxy to generate cartoDB-Positron style map tiles.
      online_resource: http://mapproxy.org/
      contact:
        organization: The Pacific Climate Impacts Consortium (PCIC)
        city: Victoria
        country: Canada
      access_constraints:
        This service is intended for private and evaluation use only.
        The data is licensed as Creative Commons Attribution-Share Alike 2.0
        (http://creativecommons.org/licenses/by-sa/2.0/)

layers:
  #sets up which layers you want to make available using the services above. You can add many, but let's stick to osm data here.
  - name: cartoDB
    title: cartoDB Layer
    sources: [proj_cache]
      
caches:
  #setup the cache for the cartoDB tiles. This cache is used by the layer above.
  source_cache:
    grids: [osm_grid]
    sources: [cartoDB_tiles]
    disable_storage: true
    format: image/png
  #reproject
  proj_cache:
    grids: [base-4326]
    sources: [source_cache]

sources:
   cartoDB_tiles:
     type: tile
     url: https://cartodb-basemaps-a.global.ssl.fastly.net/light_all/%(tms_path)s.%(format)s
     grid: osm_grid

grids:
  osm_grid:
    #this srs and origin specify a grid that can be used elsewhere in the configuration. In this example it is used for the osm_tiles source. These settings are correct for openstreetmap.org tiles.
    #The google mercator srs is used (also called EPSG:900913), and the origin of the tiles is north-west). If you get this wrong, you might very well get an all-blue world.
    srs: EPSG:900913
    origin: nw
    tile_size: [256, 256]
    
  base-4326:
    srs: EPSG:4326
    origin: nw
    tile_size: [256, 256]
    # bbox: [-180, -90, 180, 90]

globals:
  #next are some global configuration options for MapProxy. They mostly explain themselves, or can be looked-up in the MapProxy docs.
  cache:
    # where to store the cached images
    base_dir: './cache_data'
    # where to store lockfiles
    lock_dir: './cache_data/locks'

  # image/transformation options
  image:
      resampling_method: bilinear
      jpeg_quality: 90
  
